### ISSUE TITLE
Failed to install with npm i

### ISSUE THREAD

**Issue by gamerblakeman** [SystemDisc/vban-universal#1]
tried running 'npm I' in the folder and it came up with the error "npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz"
running on Mac OS High Sierra
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'vban-universal-master'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm WARN tar ENOENT: no such file or directory, lstat '/Users/user/Desktop/vban-universal-master/node_modules/.staging/app-builder-bin-7f1a292c/linux/ia32'
npm WARN tar ENOENT: no such file or directory, lstat '/Users/user/Desktop/vban-universal-master/node_modules/.staging/app-builder-bin-7f1a292c/linux/x64'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-01-26T13_25_58_012Z-debug.log`

**Comment by SystemDisc** [comment]
Apologies, I threw this project together rather quickly and haven't given it much attention. I'm not sure when I'll have time to bring it up to speed. Feel free to submit PRs which I'll probably merge or fork off of the project.

**Comment by SystemDisc** [comment]
Fixed by #2
