### ISSUE TITLE
Server bind issue

### ISSUE THREAD

**Issue by yousefalaqra** [SystemDisc/vban-universal#12]
Sometimes the code runs perfectly, and in some cases, an error occurred at `server.bind(PORT, HOST);`
I'm not sure what causes this error, especially in some cases it runs with no errors

**Comment by SystemDisc** [comment]
Is it possible you have another instance of the application running? Which OS are you running?

**Comment by yousefalaqra** [comment]
@SystemDisc 
I was able to solve the issue by setting the value of the host to be equal to the IP address of the VoiceMeeter.

**Comment by SystemDisc** [comment]
Hmm, that seems odd to me. I'm going to close this for now. If the issue comes back, please let me know what steps I would need to take to reproduce the issue.
